import React, { createContext, useContext, useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

// Translation keys
export type TranslationKey = keyof typeof translations.en;

// Translations for all supported languages
const translations = {
  en: {
    // Navigation
    home: "Home",
    products: "Products",
    cart: "Cart",
    profile: "Profile",
    settings: "Settings",
    favorites: "Favorites",
    orders: "Orders",
    
    // Home page
    newCollection: "New Collection",
    shopEssentials: "Shop the most modern essentials",
    discoverPieces: "Discover curated pieces designed for the modern lifestyle",
    exploreCollection: "Explore Collection",
    
    // Products page
    newProducts: "New Products",
    all: "All",
    noProductsFound: "No products found",
    loading: "Loading...",
    
    // Product card
    addToCart: "Add to Cart",
    addedToCart: "Added to cart!",
    
    // Cart
    yourCart: "Your Cart",
    emptyCart: "Your cart is empty",
    startShopping: "Start shopping to add items",
    continueShopping: "Continue Shopping",
    checkout: "Checkout",
    total: "Total",
    remove: "Remove",
    subtotal: "Subtotal",
    clearAll: "Clear All",
    quantity: "Quantity",
    
    // Product Detail
    youMayAlsoLike: "You may also like",
    viewAll: "View all",
    description: "Description",
    
    // Order History
    orderHistory: "Order History",
    noOrdersYet: "No orders yet",
    trackOrder: "Track",
    copyCode: "Copy",
    items: "items",
    item: "item",
    
    // Checkout
    orderSummary: "Order Summary",
    shippingInfo: "Shipping Information",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    streetAddress: "Street Address",
    city: "City",
    region: "Region",
    selectRegion: "Select a region",
    paymentMethod: "Payment Method",
    applyDiscount: "Apply Discount",
    discountCode: "Discount Code",
    enterCode: "Enter code",
    apply: "Apply",
    discount: "Discount",
    pay: "Pay",
    processing: "Processing...",
    
    // Settings
    language: "Language",
    myProfile: "My Profile",
    contactUs: "Contact Us",
    changePassword: "Change Password",
    privacyPolicy: "Privacy Policy",
    notifications: "Notifications",
    pushNotifications: "Push Notifications",
    biometric: "Biometric",
    
    // Notifications
    orderUpdates: "Order Updates",
    orderUpdatesDesc: "Get notified about your order status",
    promotions: "Promotions",
    promotionsDesc: "Receive promotional offers and deals",
    newArrivals: "New Arrivals",
    newArrivalsDesc: "Be the first to know about new products",
    priceDrops: "Price Drops",
    priceDropsDesc: "Get alerts when prices drop on favorites",
    emailNotifications: "Email Notifications",
    emailNotificationsDesc: "Receive updates via email",
    
    // Auth
    signIn: "Sign In",
    signUp: "Sign Up",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    
    // Common
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    logout: "Logout",
    back: "Back",
    next: "Next",
    submit: "Submit",
    success: "Success",
    error: "Error",
    
    // AI Features
    askAI: "Ask AI Assistant",
    aiSearch: "Describe what you're looking for...",
    aiChatPlaceholder: "Type your message...",
    aiThinking: "Thinking...",
    generateDescription: "Generate AI Description",
    generating: "Generating...",
    aiPoweredSearch: "AI-Powered Product Search",
    searchWithAI: "Searching with AI...",
    noMatchingProducts: "No products found matching your description. Try a different search.",
    describeWhatYouNeed: "Describe what you're looking for in natural language",
    searchExample: "Example: I need a casual outfit for a summer party",
    
    // Brand & Navigation
    logo: "JOYCE'S FASHION ENTERPRISE",
    fashion: "Fashion",
    gadgets: "Gadgets",
    other: "Other",
    shop: "Shop",
    admin: "Admin",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "Wear what defines you",
    springCollection: "Spring 2026 Collection",
    heroDescription: "Thoughtfully crafted essentials that blend comfort with contemporary style. Made for people who move.",
    shopNow: "Shop Now",
    newArrivalsTitle: "New Arrivals",
    happyCustomers: "Happy Customers",
    productsCount: "Products",
    avgRating: "Avg Rating",
    
    // Home Page Newsletter
    subscribeTitle: "Subscribe to our newsletter",
    subscribeSubtitle: "Get updates on new collections and special offers.",
    emailPlaceholder: "Your email address",
    subscribeBtn: "Subscribe",
    subscribingBtn: "Subscribing...",
    alreadySubscribed: "This email is already on our mailing list.",
    subscribedSuccess: "Thank you for subscribing to our newsletter.",
    alreadySubscribedTitle: "Already subscribed",
    subscribedTitle: "Subscribed!",
    subscribeError: "Failed to subscribe. Please try again.",
    
    // Settings
    general: "General",
    security: "Security",
    
    // Favorites
    loadingFavorites: "Loading favorites...",
    noFavoritesYet: "No favorites yet",
    startAddingFavorites: "Start adding items to your favorites to see them here",
    browseProducts: "Browse Products",
    share: "Share",
    copied: "Copied!",
    wishlistLinkCopied: "Wishlist link copied to clipboard!",
    failedGenerateLink: "Failed to generate share link",
    pleaseSignInWishlist: "Please sign in to share your wishlist",
    searchLanguage: "Search language...",
    languageChanged: "Language changed to",
    failedSaveLanguage: "Failed to save language preference",
  },
  es: {
    home: "Inicio",
    products: "Productos",
    cart: "Carrito",
    profile: "Perfil",
    settings: "Configuración",
    favorites: "Favoritos",
    orders: "Pedidos",
    newCollection: "Nueva Colección",
    shopEssentials: "Compra lo más moderno",
    discoverPieces: "Descubre piezas curadas para el estilo de vida moderno",
    exploreCollection: "Explorar Colección",
    newProducts: "Nuevos Productos",
    all: "Todos",
    noProductsFound: "No se encontraron productos",
    loading: "Cargando...",
    addToCart: "Añadir al Carrito",
    addedToCart: "¡Añadido al carrito!",
    yourCart: "Tu Carrito",
    emptyCart: "Tu carrito está vacío",
    startShopping: "Comienza a comprar para añadir artículos",
    continueShopping: "Continuar Comprando",
    checkout: "Pagar",
    total: "Total",
    remove: "Eliminar",
    subtotal: "Subtotal",
    clearAll: "Limpiar Todo",
    quantity: "Cantidad",
    youMayAlsoLike: "También te puede gustar",
    viewAll: "Ver todo",
    description: "Descripción",
    orderHistory: "Historial de Pedidos",
    noOrdersYet: "Sin pedidos aún",
    trackOrder: "Rastrear",
    copyCode: "Copiar",
    items: "artículos",
    item: "artículo",
    orderSummary: "Resumen del Pedido",
    shippingInfo: "Información de Envío",
    fullName: "Nombre Completo",
    email: "Correo Electrónico",
    phoneNumber: "Número de Teléfono",
    streetAddress: "Dirección",
    city: "Ciudad",
    region: "Región",
    selectRegion: "Selecciona una región",
    paymentMethod: "Método de Pago",
    applyDiscount: "Aplicar Descuento",
    discountCode: "Código de Descuento",
    enterCode: "Ingresa el código",
    apply: "Aplicar",
    discount: "Descuento",
    pay: "Pagar",
    processing: "Procesando...",
    language: "Idioma",
    myProfile: "Mi Perfil",
    contactUs: "Contáctanos",
    changePassword: "Cambiar Contraseña",
    privacyPolicy: "Política de Privacidad",
    notifications: "Notificaciones",
    pushNotifications: "Notificaciones Push",
    biometric: "Biométrico",
    orderUpdates: "Actualizaciones de Pedidos",
    orderUpdatesDesc: "Recibe notificaciones sobre el estado de tu pedido",
    promotions: "Promociones",
    promotionsDesc: "Recibe ofertas promocionales",
    newArrivals: "Nuevas Llegadas",
    newArrivalsDesc: "Sé el primero en conocer nuevos productos",
    priceDrops: "Bajadas de Precio",
    priceDropsDesc: "Recibe alertas cuando bajen los precios",
    emailNotifications: "Notificaciones por Email",
    emailNotificationsDesc: "Recibe actualizaciones por correo",
    signIn: "Iniciar Sesión",
    signUp: "Registrarse",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    noAccount: "¿No tienes cuenta?",
    haveAccount: "¿Ya tienes cuenta?",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    search: "Buscar",
    logout: "Cerrar Sesión",
    back: "Atrás",
    next: "Siguiente",
    submit: "Enviar",
    success: "Éxito",
    error: "Error",
    askAI: "Preguntar al Asistente IA",
    aiSearch: "Describe lo que buscas...",
    aiChatPlaceholder: "Escribe tu mensaje...",
    aiThinking: "Pensando...",
    generateDescription: "Generar Descripción IA",
    generating: "Generando...",
    aiPoweredSearch: "Búsqueda con IA",
    searchWithAI: "Buscando con IA...",
    noMatchingProducts: "No se encontraron productos. Intenta otra búsqueda.",
    describeWhatYouNeed: "Describe lo que buscas en lenguaje natural",
    searchExample: "Ejemplo: Necesito un atuendo casual para una fiesta de verano",
    
    // Brand & Navigation
    logo: "EMPRESA DE MODA DE JOYCE",
    fashion: "Moda",
    gadgets: "Accesorios",
    other: "Otros",
    shop: "Tienda",
    admin: "Admin",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "Lleva lo que te define",
    springCollection: "Colección Primavera 2026",
    heroDescription: "Esenciales cuidadosamente elaborados que combinan comodidad con estilo contemporáneo. Hechos para personas en movimiento.",
    shopNow: "Comprar Ahora",
    newArrivalsTitle: "Nuevas Llegadas",
    happyCustomers: "Clientes Felices",
    productsCount: "Productos",
    avgRating: "Clasificación Promedio",
    
    // Home Page Newsletter
    subscribeTitle: "Suscríbete a nuestro boletín",
    subscribeSubtitle: "Recibe actualizaciones sobre nuevas colecciones y ofertas especiales.",
    emailPlaceholder: "Tu dirección de correo",
    subscribeBtn: "Suscribirse",
    subscribingBtn: "Suscribiéndose...",
    alreadySubscribed: "Este correo ya está en nuestra lista de correo.",
    subscribedSuccess: "Gracias por suscribirte a nuestro boletín.",
    alreadySubscribedTitle: "Ya suscrito",
    subscribedTitle: "¡Suscrito!",
    subscribeError: "Error al suscribirse. Inténtalo de nuevo.",
    
    // Settings
    general: "General",
    security: "Seguridad",
    
    // Favorites
    loadingFavorites: "Cargando favoritos...",
    noFavoritesYet: "Aún no hay favoritos",
    startAddingFavorites: "Comienza a añadir artículos a tus favoritos para verlos aquí",
    browseProducts: "Explorar Productos",
    share: "Compartir",
    copied: "¡Copiado!",
    wishlistLinkCopied: "¡Enlace de lista de deseos copiado al portapapeles!",
    failedGenerateLink: "Error al generar enlace para compartir",
    pleaseSignInWishlist: "Inicia sesión para compartir tu lista de deseos",
    searchLanguage: "Buscar idioma...",
    languageChanged: "Idioma cambiado a",
    failedSaveLanguage: "Error al guardar la preferencia de idioma",
  },
  fr: {
    home: "Accueil",
    products: "Produits",
    cart: "Panier",
    profile: "Profil",
    settings: "Paramètres",
    favorites: "Favoris",
    orders: "Commandes",
    newCollection: "Nouvelle Collection",
    shopEssentials: "Achetez les essentiels modernes",
    discoverPieces: "Découvrez des pièces conçues pour le style de vie moderne",
    exploreCollection: "Explorer la Collection",
    newProducts: "Nouveaux Produits",
    all: "Tous",
    noProductsFound: "Aucun produit trouvé",
    loading: "Chargement...",
    addToCart: "Ajouter au Panier",
    addedToCart: "Ajouté au panier!",
    yourCart: "Votre Panier",
    emptyCart: "Votre panier est vide",
    startShopping: "Commencez vos achats",
    continueShopping: "Continuer les Achats",
    checkout: "Commander",
    total: "Total",
    remove: "Supprimer",
    orderSummary: "Résumé de la Commande",
    shippingInfo: "Informations de Livraison",
    fullName: "Nom Complet",
    email: "Email",
    phoneNumber: "Numéro de Téléphone",
    streetAddress: "Adresse",
    city: "Ville",
    region: "Région",
    selectRegion: "Sélectionnez une région",
    paymentMethod: "Mode de Paiement",
    applyDiscount: "Appliquer une Réduction",
    discountCode: "Code de Réduction",
    enterCode: "Entrez le code",
    apply: "Appliquer",
    discount: "Réduction",
    pay: "Payer",
    processing: "Traitement...",
    language: "Langue",
    myProfile: "Mon Profil",
    contactUs: "Nous Contacter",
    changePassword: "Changer le Mot de Passe",
    privacyPolicy: "Politique de Confidentialité",
    notifications: "Notifications",
    pushNotifications: "Notifications Push",
    biometric: "Biométrique",
    signIn: "Se Connecter",
    signUp: "S'inscrire",
    password: "Mot de Passe",
    confirmPassword: "Confirmer le Mot de Passe",
    forgotPassword: "Mot de passe oublié?",
    noAccount: "Pas de compte?",
    haveAccount: "Déjà un compte?",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    search: "Rechercher",
    logout: "Déconnexion",
    back: "Retour",
    next: "Suivant",
    submit: "Soumettre",
    success: "Succès",
    error: "Erreur",
    askAI: "Demander à l'Assistant IA",
    aiSearch: "Décrivez ce que vous cherchez...",
    aiChatPlaceholder: "Tapez votre message...",
    aiThinking: "Réflexion...",
    generateDescription: "Générer Description IA",
    generating: "Génération...",
    
    // Brand & Navigation
    logo: "ENTREPRISE DE MODE DE JOYCE",
    fashion: "Mode",
    gadgets: "Gadgets",
    other: "Autre",
    shop: "Boutique",
    admin: "Admin",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "Portez ce qui vous définit",
    springCollection: "Collection Printemps 2026",
    heroDescription: "Des essentiels soigneusement conçus qui allient confort et style contemporain. Conçus pour les personnes en mouvement.",
    shopNow: "Acheter Maintenant",
    newArrivalsTitle: "Nouveautés",
    happyCustomers: "Clients Heureux",
    productsCount: "Produits",
    avgRating: "Note Moyenne",
    
    // Home Page Newsletter
    subscribeTitle: "Abonnez-vous à notre newsletter",
    subscribeSubtitle: "Recevez des mises à jour sur les nouvelles collections et les offres spéciales.",
    emailPlaceholder: "Votre adresse e-mail",
    subscribeBtn: "S'abonner",
    subscribingBtn: "Inscription...",
    alreadySubscribed: "Cet e-mail est déjà sur notre liste de diffusion.",
    subscribedSuccess: "Merci de vous être abonné à notre newsletter.",
    alreadySubscribedTitle: "Déjà abonné",
    subscribedTitle: "Abonné !",
    subscribeError: "Échec de l'abonnement. Veuillez réessayer.",
    
    // Settings
    general: "Général",
    security: "Sécurité",
    
    // Favorites
    loadingFavorites: "Chargement des favoris...",
    noFavoritesYet: "Pas encore de favoris",
    startAddingFavorites: "Ajoutez des articles à vos favoris pour les voir ici",
    browseProducts: "Parcourir les Produits",
    share: "Partager",
    copied: "Copié !",
    wishlistLinkCopied: "Lien de la liste de souhaits copié dans le presse-papiers !",
    failedGenerateLink: "Échec de la génération du lien de partage",
    pleaseSignInWishlist: "Veuillez vous connecter pour partager votre liste de souhaits",
    searchLanguage: "Rechercher une langue...",
    languageChanged: "Langue changée en",
    failedSaveLanguage: "Échec de l'enregistrement de la préférence de langue",
  },
  de: {
    home: "Startseite",
    products: "Produkte",
    cart: "Warenkorb",
    profile: "Profil",
    settings: "Einstellungen",
    favorites: "Favoriten",
    orders: "Bestellungen",
    newCollection: "Neue Kollektion",
    shopEssentials: "Shoppen Sie die modernsten Essentials",
    discoverPieces: "Entdecken Sie kuratierte Stücke für den modernen Lebensstil",
    exploreCollection: "Kollektion Erkunden",
    newProducts: "Neue Produkte",
    all: "Alle",
    noProductsFound: "Keine Produkte gefunden",
    loading: "Laden...",
    addToCart: "In den Warenkorb",
    addedToCart: "Zum Warenkorb hinzugefügt!",
    yourCart: "Ihr Warenkorb",
    emptyCart: "Ihr Warenkorb ist leer",
    startShopping: "Beginnen Sie mit dem Einkaufen",
    continueShopping: "Weiter Einkaufen",
    checkout: "Zur Kasse",
    total: "Gesamt",
    remove: "Entfernen",
    orderSummary: "Bestellübersicht",
    shippingInfo: "Versandinformationen",
    fullName: "Vollständiger Name",
    email: "E-Mail",
    phoneNumber: "Telefonnummer",
    streetAddress: "Straßenadresse",
    city: "Stadt",
    region: "Region",
    selectRegion: "Region auswählen",
    paymentMethod: "Zahlungsmethode",
    applyDiscount: "Rabatt Anwenden",
    discountCode: "Rabattcode",
    enterCode: "Code eingeben",
    apply: "Anwenden",
    discount: "Rabatt",
    pay: "Bezahlen",
    processing: "Verarbeitung...",
    language: "Sprache",
    myProfile: "Mein Profil",
    contactUs: "Kontaktieren Sie Uns",
    changePassword: "Passwort Ändern",
    privacyPolicy: "Datenschutzrichtlinie",
    notifications: "Benachrichtigungen",
    pushNotifications: "Push-Benachrichtigungen",
    biometric: "Biometrie",
    signIn: "Anmelden",
    signUp: "Registrieren",
    password: "Passwort",
    confirmPassword: "Passwort Bestätigen",
    forgotPassword: "Passwort vergessen?",
    noAccount: "Kein Konto?",
    haveAccount: "Bereits ein Konto?",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    search: "Suchen",
    logout: "Abmelden",
    back: "Zurück",
    next: "Weiter",
    submit: "Absenden",
    success: "Erfolg",
    error: "Fehler",
    askAI: "KI-Assistent Fragen",
    aiSearch: "Beschreiben Sie, was Sie suchen...",
    aiChatPlaceholder: "Nachricht eingeben...",
    aiThinking: "Nachdenken...",
    generateDescription: "KI-Beschreibung Generieren",
    generating: "Generieren...",
    
    // Brand & Navigation
    logo: "JOYCE'S FASHION ENTERPRISE",
    fashion: "Mode",
    gadgets: "Gadgets",
    other: "Andere",
    shop: "Shop",
    admin: "Admin",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "Trage, was dich ausmacht",
    springCollection: "Frühjahrskollektion 2026",
    heroDescription: "Durchdachte Essentials, die Komfort mit modernem Stil verbinden. Gemacht für Menschen in Bewegung.",
    shopNow: "Jetzt Shoppen",
    newArrivalsTitle: "Neuheiten",
    happyCustomers: "Zufriedene Kunden",
    productsCount: "Produkte",
    avgRating: "Ø Bewertung",
    
    // Home Page Newsletter
    subscribeTitle: "Abonnieren Sie unseren Newsletter",
    subscribeSubtitle: "Erhalten Sie Updates zu neuen Kollektionen und Sonderangeboten.",
    emailPlaceholder: "Ihre E-Mail-Adresse",
    subscribeBtn: "Abonnieren",
    subscribingBtn: "Abonnieren...",
    alreadySubscribed: "Diese E-Mail ist bereits in unserem Verteiler.",
    subscribedSuccess: "Danke, dass Sie unseren Newsletter abonniert haben.",
    alreadySubscribedTitle: "Bereits abonniert",
    subscribedTitle: "Abonniert!",
    subscribeError: "Abonnieren fehlgeschlagen. Bitte versuchen Sie es erneut.",
    
    // Settings
    general: "Allgemein",
    security: "Sicherheit",
    
    // Favorites
    loadingFavorites: "Favoriten werden geladen...",
    noFavoritesYet: "Noch keine Favoriten",
    startAddingFavorites: "Fügen Sie Artikel zu Ihren Favoriten hinzu, um sie hier zu sehen",
    browseProducts: "Produkte Durchsuchen",
    share: "Teilen",
    copied: "Kopiert!",
    wishlistLinkCopied: "Wunschzettel-Link in die Zwischenablage kopiert!",
    failedGenerateLink: "Freigabelink konnte nicht erstellt werden",
    pleaseSignInWishlist: "Bitte melden Sie sich an, um Ihren Wunschzettel zu teilen",
    searchLanguage: "Sprache suchen...",
    languageChanged: "Sprache geändert auf",
    failedSaveLanguage: "Fehler beim Speichern der Spracheinstellung",
  },
  zh: {
    home: "首页",
    products: "产品",
    cart: "购物车",
    profile: "个人资料",
    settings: "设置",
    favorites: "收藏",
    orders: "订单",
    newCollection: "新品系列",
    shopEssentials: "购买最现代的必需品",
    discoverPieces: "发现为现代生活方式设计的精选单品",
    exploreCollection: "探索系列",
    newProducts: "新产品",
    all: "全部",
    noProductsFound: "未找到产品",
    loading: "加载中...",
    addToCart: "加入购物车",
    addedToCart: "已加入购物车!",
    yourCart: "您的购物车",
    emptyCart: "购物车为空",
    startShopping: "开始购物添加商品",
    continueShopping: "继续购物",
    checkout: "结账",
    total: "总计",
    remove: "删除",
    orderSummary: "订单摘要",
    shippingInfo: "配送信息",
    fullName: "全名",
    email: "电子邮件",
    phoneNumber: "电话号码",
    streetAddress: "街道地址",
    city: "城市",
    region: "地区",
    selectRegion: "选择地区",
    paymentMethod: "支付方式",
    applyDiscount: "应用折扣",
    discountCode: "折扣码",
    enterCode: "输入代码",
    apply: "应用",
    discount: "折扣",
    pay: "支付",
    processing: "处理中...",
    language: "语言",
    myProfile: "我的资料",
    contactUs: "联系我们",
    changePassword: "更改密码",
    privacyPolicy: "隐私政策",
    notifications: "通知",
    pushNotifications: "推送通知",
    biometric: "生物识别",
    signIn: "登录",
    signUp: "注册",
    password: "密码",
    confirmPassword: "确认密码",
    forgotPassword: "忘记密码?",
    noAccount: "没有账户?",
    haveAccount: "已有账户?",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    search: "搜索",
    logout: "登出",
    back: "返回",
    next: "下一步",
    submit: "提交",
    success: "成功",
    error: "错误",
    askAI: "询问AI助手",
    aiSearch: "描述你在找什么...",
    aiChatPlaceholder: "输入消息...",
    aiThinking: "思考中...",
    generateDescription: "生成AI描述",
    generating: "生成中...",
    
    // Brand & Navigation
    logo: "JOYCE的时尚企业",
    fashion: "时尚",
    gadgets: "数码配件",
    other: "其他",
    shop: "商店",
    admin: "管理员",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "穿出你的个性",
    springCollection: "2026春季系列",
    heroDescription: "精心打造的单品，融舒适与现代风格于一体。为前行者而生。",
    shopNow: "立即选购",
    newArrivalsTitle: "新品推荐",
    happyCustomers: "满意客户",
    productsCount: "产品数量",
    avgRating: "平均评分",
    
    // Home Page Newsletter
    subscribeTitle: "订阅我们的邮件",
    subscribeSubtitle: "获取新品系列和特别优惠的最新动态。",
    emailPlaceholder: "您的电子邮箱",
    subscribeBtn: "订阅",
    subscribingBtn: "订阅中...",
    alreadySubscribed: "该邮箱已在我们的订阅列表中。",
    subscribedSuccess: "感谢您订阅我们的邮件通知。",
    alreadySubscribedTitle: "已订阅",
    subscribedTitle: "订阅成功！",
    subscribeError: "订阅失败，请重试。",
    
    // Settings
    general: "通用",
    security: "安全",
    
    // Favorites
    loadingFavorites: "正在加载收藏夹...",
    noFavoritesYet: "暂无收藏",
    startAddingFavorites: "开始添加商品到收藏夹以在此处查看",
    browseProducts: "浏览产品",
    share: "分享",
    copied: "已复制！",
    wishlistLinkCopied: "心愿单链接已复制到剪贴板！",
    failedGenerateLink: "无法生成分享链接",
    pleaseSignInWishlist: "请先登录以分享您的心愿单",
    searchLanguage: "搜索语言...",
    languageChanged: "语言已更改为",
    failedSaveLanguage: "保存语言首选项失败",
  },
  tw: {
    home: "主页",
    products: "产品",
    cart: "购物车",
    profile: "个人资料",
    settings: "设置",
    favorites: "收藏",
    orders: "订单",
    newCollection: "新品系列",
    shopEssentials: "购买最新的必需品",
    discoverPieces: "发现现代生活方式的精选单品",
    exploreCollection: "探索系列",
    newProducts: "新产品",
    all: "全部",
    noProductsFound: "未找到产品",
    loading: "加载中...",
    addToCart: "加入购物车",
    addedToCart: "已加入购物车!",
    yourCart: "您的购物车",
    emptyCart: "购物车为空",
    startShopping: "开始购物",
    continueShopping: "继续购物",
    checkout: "结账",
    total: "总计",
    remove: "删除",
    orderSummary: "订单摘要",
    shippingInfo: "配送信息",
    fullName: "全名",
    email: "电子邮件",
    phoneNumber: "电话号码",
    streetAddress: "地址",
    city: "城市",
    region: "地区",
    selectRegion: "选择地区",
    paymentMethod: "支付方式",
    applyDiscount: "应用折扣",
    discountCode: "折扣码",
    enterCode: "输入代码",
    apply: "应用",
    discount: "折扣",
    pay: "支付",
    processing: "处理中...",
    language: "语言",
    myProfile: "我的资料",
    contactUs: "联系我们",
    changePassword: "更改密码",
    privacyPolicy: "隐私政策",
    notifications: "通知",
    pushNotifications: "推送通知",
    biometric: "生物识别",
    signIn: "登录",
    signUp: "注册",
    password: "密码",
    confirmPassword: "确认密码",
    forgotPassword: "忘记密码?",
    noAccount: "没有账户?",
    haveAccount: "已有账户?",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    search: "搜索",
    logout: "登出",
    back: "返回",
    next: "下一步",
    submit: "提交",
    success: "成功",
    error: "错误",
    askAI: "询问AI助手",
    aiSearch: "描述你在找什么...",
    aiChatPlaceholder: "输入消息...",
    aiThinking: "思考中...",
    generateDescription: "生成AI描述",
    generating: "生成中...",
    
    // Brand & Navigation
    logo: "JOYCE的時尚企業",
    fashion: "時尚",
    gadgets: "數碼配件",
    other: "其他",
    shop: "商店",
    admin: "管理員",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "穿出你的個性",
    springCollection: "2026春季系列",
    heroDescription: "精心打造的單品，融舒適與現代風格於一體。為前行者而生。",
    shopNow: "立即選購",
    newArrivalsTitle: "新品推薦",
    happyCustomers: "滿意客戶",
    productsCount: "產品數量",
    avgRating: "平均評分",
    
    // Home Page Newsletter
    subscribeTitle: "訂閱我們的郵件",
    subscribeSubtitle: "獲取新品系列和特別優惠的最新動態。",
    emailPlaceholder: "您的電子郵箱",
    subscribeBtn: "訂閱",
    subscribingBtn: "訂閱中...",
    alreadySubscribed: "該郵箱已在我們的訂閱列表中。",
    subscribedSuccess: "感謝您訂閱我們的郵件通知。",
    alreadySubscribedTitle: "已訂閱",
    subscribedTitle: "訂閱成功！",
    subscribeError: "訂閱失敗，請重試。",
    
    // Settings
    general: "通用",
    security: "安全",
    
    // Favorites
    loadingFavorites: "正在加載收藏夾...",
    noFavoritesYet: "暫無收藏",
    startAddingFavorites: "開始添加商品到收藏夾以在此處查看",
    browseProducts: "瀏覽產品",
    share: "分享",
    copied: "已複製！",
    wishlistLinkCopied: "心願單鏈接已複製到剪貼板！",
    failedGenerateLink: "無法生成分享鏈接",
    pleaseSignInWishlist: "請先登錄以分享您的心願單",
    searchLanguage: "搜尋語言...",
    languageChanged: "語言已更改為",
    failedSaveLanguage: "儲存語言首選項失敗",
  },
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    cart: "السلة",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    favorites: "المفضلة",
    orders: "الطلبات",
    newCollection: "مجموعة جديدة",
    shopEssentials: "تسوق أحدث الأساسيات",
    discoverPieces: "اكتشف قطعًا مختارة لأسلوب الحياة العصري",
    exploreCollection: "استكشف المجموعة",
    newProducts: "منتجات جديدة",
    all: "الكل",
    noProductsFound: "لم يتم العثور على منتجات",
    loading: "جارٍ التحميل...",
    addToCart: "أضف إلى السلة",
    addedToCart: "تمت الإضافة إلى السلة!",
    yourCart: "سلتك",
    emptyCart: "سلتك فارغة",
    startShopping: "ابدأ التسوق لإضافة المنتجات",
    continueShopping: "متابعة التسوق",
    checkout: "الدفع",
    total: "المجموع",
    remove: "إزالة",
    orderSummary: "ملخص الطلب",
    shippingInfo: "معلومات الشحن",
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    streetAddress: "العنوان",
    city: "المدينة",
    region: "المنطقة",
    selectRegion: "اختر منطقة",
    paymentMethod: "طريقة الدفع",
    applyDiscount: "تطبيق الخصم",
    discountCode: "رمز الخصم",
    enterCode: "أدخل الرمز",
    apply: "تطبيق",
    discount: "الخصم",
    pay: "ادفع",
    processing: "جارٍ المعالجة...",
    language: "اللغة",
    myProfile: "ملفي الشخصي",
    contactUs: "اتصل بنا",
    changePassword: "تغيير كلمة المرور",
    privacyPolicy: "سياسة الخصوصية",
    notifications: "الإشعارات",
    pushNotifications: "إشعارات الدفع",
    biometric: "البصمة",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    search: "بحث",
    logout: "تسجيل الخروج",
    back: "رجوع",
    next: "التالي",
    submit: "إرسال",
    success: "نجاح",
    error: "خطأ",
    askAI: "اسأل مساعد الذكاء الاصطناعي",
    aiSearch: "صف ما تبحث عنه...",
    aiChatPlaceholder: "اكتب رسالتك...",
    aiThinking: "جارٍ التفكير...",
    generateDescription: "إنشاء وصف بالذكاء الاصطناعي",
    generating: "جارٍ الإنشاء...",
    
    // Brand & Navigation
    logo: "مؤسسة جويس للأزياء",
    fashion: "موضة",
    gadgets: "أجهزة وأدوات",
    other: "أخرى",
    shop: "متجر",
    admin: "مسؤول",
    
    // Home Page Hero & Stats
    wearWhatDefinesYou: "ارتدِ ما يعبر عنك",
    springCollection: "مجموعة ربيع 2026",
    heroDescription: "أساسيات صُنعت بعناية تجمع بين الراحة والأسلوب المعاصر. مصممة لمن هم في حركة دائمًا.",
    shopNow: "تسوق الآن",
    newArrivalsTitle: "وصل حديثاً",
    happyCustomers: "عملاء سعداء",
    productsCount: "منتجات",
    avgRating: "متوسط التقييم",
    
    // Home Page Newsletter
    subscribeTitle: "اشترك في نشرتنا الإخبارية",
    subscribeSubtitle: "احصل على تحديثات حول المجموعات الجديدة والعروض الخاصة.",
    emailPlaceholder: "عنوان بريدك الإلكتروني",
    subscribeBtn: "اشتراك",
    subscribingBtn: "جاري الاشتراك...",
    alreadySubscribed: "هذا البريد الإلكتروني مسجل بالفعل في قائمتنا البريدية.",
    subscribedSuccess: "شكرًا لك على الاشتراك في نشرتنا الإخبارية.",
    alreadySubscribedTitle: "مشترك بالفعل",
    subscribedTitle: "تم الاشتراك!",
    subscribeError: "فشل الاشتراك. يرجى المحاولة مرة أخرى.",
    
    // Settings
    general: "عام",
    security: "الأمان",
    
    // Favorites
    loadingFavorites: "جاري تحميل المفضلة...",
    noFavoritesYet: "لا توجد مفضلة بعد",
    startAddingFavorites: "ابدأ بإضافة العناصر إلى المفضلة لتراها هنا",
    browseProducts: "تصفح المنتجات",
    share: "مشاركة",
    copied: "تم النسخ!",
    wishlistLinkCopied: "تم نسخ رابط قائمة الأمنيات إلى الحافظة!",
    failedGenerateLink: "فشل إنشاء رابط المشاركة",
    pleaseSignInWishlist: "يرجى تسجيل الدخول لمشاركة قائمة أمنياتك",
    searchLanguage: "البحث عن اللغة...",
    languageChanged: "تم تغيير اللغة إلى",
    failedSaveLanguage: "فشل في حفظ تفضيل اللغة",
  },
};

export type SupportedLanguage = keyof typeof translations;

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
});

export const useLanguage = () => useContext(LanguageContext);

const RTL_LANGUAGES = ["ar", "he", "fa", "ur"];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>("en");
  const { user } = useAuth();

  useEffect(() => {
    const fetchLanguage = async () => {
      if (user) {
        const { data } = await supabase
          .from("profiles")
          .select("language_preference")
          .eq("id", user.id)
          .single();
        
        if (data?.language_preference && translations[data.language_preference as SupportedLanguage]) {
          setLanguageState(data.language_preference as SupportedLanguage);
        }
      }
    };
    fetchLanguage();
  }, [user]);

  const setLanguage = useCallback(async (lang: SupportedLanguage) => {
    setLanguageState(lang);
    if (user) {
      await supabase
        .from("profiles")
        .update({ language_preference: lang })
        .eq("id", user.id);
    }
  }, [user]);

  const t = useCallback((key: TranslationKey): string => {
    const langTranslations = translations[language] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  }, [language]);

  const isRTL = RTL_LANGUAGES.includes(language);

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};
