-- Migration: Seed delivery towns for Greater Accra
INSERT INTO public.delivery_fees (region, city, town, fee, is_active)
VALUES
  ('Greater Accra', 'Ablekuma North', 'New Achimota', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'New Dansoman', 20.00, true),
  ('Greater Accra', 'Accra', 'Abeka', 20.00, true),
  ('Greater Accra', 'Accra', 'Abeka Lapaz', 20.00, true),
  ('Greater Accra', 'Accra', 'Abelemkpe', 20.00, true),
  ('Greater Accra', 'Accra', 'Abossey Okai', 20.00, true),
  ('Greater Accra', 'Accra', 'Accra Central', 20.00, true),
  ('Greater Accra', 'Accra', 'Accra New Town', 20.00, true),
  ('Greater Accra', 'Accra', 'Achimota', 20.00, true),
  ('Greater Accra', 'Accra', 'Adabraka', 20.00, true),
  ('Greater Accra', 'Accra', 'Adjiringanor', 20.00, true),
  ('Greater Accra', 'Accra', 'Agbogba', 20.00, true),
  ('Greater Accra', 'Accra', 'Airport Hills', 20.00, true),
  ('Greater Accra', 'Accra', 'Airport Residential', 20.00, true),
  ('Greater Accra', 'Accra', 'Alajo', 20.00, true),
  ('Greater Accra', 'Accra', 'Amasaman', 20.00, true),
  ('Greater Accra', 'Accra', 'American House', 20.00, true),
  ('Greater Accra', 'Accra', 'Anyaa', 20.00, true),
  ('Greater Accra', 'Accra', 'Aplaku', 20.00, true),
  ('Greater Accra', 'Accra', 'Ashalley Botwe', 20.00, true),
  ('Greater Accra', 'Accra', 'Ashongman', 20.00, true),
  ('Greater Accra', 'Accra', 'Asylum Down', 20.00, true),
  ('Greater Accra', 'Accra', 'Atomic', 20.00, true),
  ('Greater Accra', 'Accra', 'Avenor', 20.00, true),
  ('Greater Accra', 'Accra', 'Awoshie', 20.00, true),
  ('Greater Accra', 'Accra', 'Baatsona', 20.00, true),
  ('Greater Accra', 'Accra', 'Bawaleshie', 20.00, true),
  ('Greater Accra', 'Accra', 'Bortianor', 20.00, true),
  ('Greater Accra', 'Accra', 'Cantonments', 20.00, true),
  ('Greater Accra', 'Accra', 'Chorkor', 20.00, true),
  ('Greater Accra', 'Accra', 'Dansoman', 20.00, true),
  ('Greater Accra', 'Accra', 'Darkuman', 20.00, true),
  ('Greater Accra', 'Accra', 'Dome', 20.00, true),
  ('Greater Accra', 'Accra', 'Dzorwulu', 20.00, true),
  ('Greater Accra', 'Accra', 'East Legon', 20.00, true),
  ('Greater Accra', 'Accra', 'East Legon Hills', 20.00, true),
  ('Greater Accra', 'Accra', 'Faajiemohe', 20.00, true),
  ('Greater Accra', 'Accra', 'Gbawe', 20.00, true),
  ('Greater Accra', 'Accra', 'Glefe', 20.00, true),
  ('Greater Accra', 'Accra', 'Haatso', 20.00, true),
  ('Greater Accra', 'Accra', 'Jamestown', 20.00, true),
  ('Greater Accra', 'Accra', 'Kanda', 20.00, true),
  ('Greater Accra', 'Accra', 'Kaneshie', 20.00, true),
  ('Greater Accra', 'Accra', 'Klagon', 20.00, true),
  ('Greater Accra', 'Accra', 'Kokomlemle', 20.00, true),
  ('Greater Accra', 'Accra', 'Kokrobite', 20.00, true),
  ('Greater Accra', 'Accra', 'Korle Gonno', 20.00, true),
  ('Greater Accra', 'Accra', 'Kotobabi', 20.00, true),
  ('Greater Accra', 'Accra', 'Kwabenya', 20.00, true),
  ('Greater Accra', 'Accra', 'Kwashieman', 20.00, true),
  ('Greater Accra', 'Accra', 'La', 20.00, true),
  ('Greater Accra', 'Accra', 'Labadi', 20.00, true),
  ('Greater Accra', 'Accra', 'Labone', 20.00, true),
  ('Greater Accra', 'Accra', 'Lakeside', 20.00, true),
  ('Greater Accra', 'Accra', 'Lapaz', 20.00, true),
  ('Greater Accra', 'Accra', 'Lartebiokorshie', 20.00, true),
  ('Greater Accra', 'Accra', 'Madina', 20.00, true),
  ('Greater Accra', 'Accra', 'Makola', 20.00, true),
  ('Greater Accra', 'Accra', 'Mallam', 20.00, true),
  ('Greater Accra', 'Accra', 'Mamobi', 20.00, true),
  ('Greater Accra', 'Accra', 'Mamprobi', 20.00, true),
  ('Greater Accra', 'Accra', 'Mataheko', 20.00, true),
  ('Greater Accra', 'Accra', 'McCarthy Hill', 20.00, true),
  ('Greater Accra', 'Accra', 'Mile 7', 20.00, true),
  ('Greater Accra', 'Accra', 'Mile 9', 20.00, true),
  ('Greater Accra', 'Accra', 'New Town', 20.00, true),
  ('Greater Accra', 'Accra', 'Ngleshie Amanfrom', 20.00, true),
  ('Greater Accra', 'Accra', 'Nima', 20.00, true),
  ('Greater Accra', 'Accra', 'North Legon', 20.00, true),
  ('Greater Accra', 'Accra', 'North Ridge', 20.00, true),
  ('Greater Accra', 'Accra', 'Nungua', 20.00, true),
  ('Greater Accra', 'Accra', 'Nungua Estates', 20.00, true),
  ('Greater Accra', 'Accra', 'Oblogo', 20.00, true),
  ('Greater Accra', 'Accra', 'Odorkor', 20.00, true),
  ('Greater Accra', 'Accra', 'Ofankor', 20.00, true),
  ('Greater Accra', 'Accra', 'Ogbojo', 20.00, true),
  ('Greater Accra', 'Accra', 'Okponglo', 20.00, true),
  ('Greater Accra', 'Accra', 'Osu', 20.00, true),
  ('Greater Accra', 'Accra', 'Pig Farm', 20.00, true),
  ('Greater Accra', 'Accra', 'Pokuase', 20.00, true),
  ('Greater Accra', 'Accra', 'Ridge', 20.00, true),
  ('Greater Accra', 'Accra', 'Ringway', 20.00, true),
  ('Greater Accra', 'Accra', 'Roman Ridge', 20.00, true),
  ('Greater Accra', 'Accra', 'Sakumono', 20.00, true),
  ('Greater Accra', 'Accra', 'Santa Maria', 20.00, true),
  ('Greater Accra', 'Accra', 'Shiashie', 20.00, true),
  ('Greater Accra', 'Accra', 'Sowutuom', 20.00, true),
  ('Greater Accra', 'Accra', 'Spintex', 20.00, true),
  ('Greater Accra', 'Accra', 'Taifa', 20.00, true),
  ('Greater Accra', 'Accra', 'Tesano', 20.00, true),
  ('Greater Accra', 'Accra', 'Teshie', 20.00, true),
  ('Greater Accra', 'Accra', 'Tetegu', 20.00, true),
  ('Greater Accra', 'Accra', 'Trade Fair', 20.00, true),
  ('Greater Accra', 'Accra', 'Trasacco', 20.00, true),
  ('Greater Accra', 'Accra', 'Tudu', 20.00, true),
  ('Greater Accra', 'Accra', 'Ussher Town', 20.00, true),
  ('Greater Accra', 'Accra', 'Victoriaborg', 20.00, true),
  ('Greater Accra', 'Accra', 'Weija', 20.00, true),
  ('Greater Accra', 'Ada East', 'Ada', 20.00, true),
  ('Greater Accra', 'Ada East', 'Ada Foah', 20.00, true),
  ('Greater Accra', 'Ada East', 'Ada Panya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Agbenyegakope', 20.00, true),
  ('Greater Accra', 'Ada East', 'Anyamam', 20.00, true),
  ('Greater Accra', 'Ada East', 'Azizanya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Big Ada', 20.00, true),
  ('Greater Accra', 'Ada East', 'Fiakonya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Gikedokum', 20.00, true),
  ('Greater Accra', 'Ada East', 'Goi', 20.00, true),
  ('Greater Accra', 'Ada East', 'Kajanya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Kasseh', 20.00, true),
  ('Greater Accra', 'Ada East', 'Lolonyo', 20.00, true),
  ('Greater Accra', 'Ada East', 'Lorlorvor', 20.00, true),
  ('Greater Accra', 'Ada East', 'Magbomada', 20.00, true),
  ('Greater Accra', 'Ada East', 'Maledjor', 20.00, true),
  ('Greater Accra', 'Ada East', 'Mangotsonya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Manya Jorpanya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Matsekope', 20.00, true),
  ('Greater Accra', 'Ada East', 'Nyapienya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Nyigbenya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Pena', 20.00, true),
  ('Greater Accra', 'Ada East', 'Pute', 20.00, true),
  ('Greater Accra', 'Ada East', 'Sege', 20.00, true),
  ('Greater Accra', 'Ada East', 'Some', 20.00, true),
  ('Greater Accra', 'Ada East', 'Songonya', 20.00, true),
  ('Greater Accra', 'Ada East', 'Sota', 20.00, true),
  ('Greater Accra', 'Ada East', 'Sugbanyate', 20.00, true),
  ('Greater Accra', 'Ada East', 'Tesa', 20.00, true),
  ('Greater Accra', 'Ada East', 'Toflokpo', 20.00, true),
  ('Greater Accra', 'Ada East', 'Totope', 20.00, true),
  ('Greater Accra', 'Ada East', 'Wuonyi', 20.00, true),
  ('Greater Accra', 'Ada East', 'Zanidaw', 20.00, true),
  ('Greater Accra', 'Ada West', 'Agorkedzi', 20.00, true),
  ('Greater Accra', 'Ada West', 'Akplabanya', 20.00, true),
  ('Greater Accra', 'Ada West', 'Anyakpor', 20.00, true),
  ('Greater Accra', 'Ada West', 'Asigbekope', 20.00, true),
  ('Greater Accra', 'Ada West', 'Doryumu', 20.00, true),
  ('Greater Accra', 'Ada West', 'Koluedor', 20.00, true),
  ('Greater Accra', 'Ada West', 'Sege Donya', 20.00, true),
  ('Greater Accra', 'Adenta', 'Adenta', 20.00, true),
  ('Greater Accra', 'Adenta', 'Adenta Housing Down', 20.00, true),
  ('Greater Accra', 'Adenta', 'Amrahia', 20.00, true),
  ('Greater Accra', 'Adenta', 'Ashiyie', 20.00, true),
  ('Greater Accra', 'Adenta', 'Frafraha', 20.00, true),
  ('Greater Accra', 'Adenta', 'Nanakrom', 20.00, true),
  ('Greater Accra', 'Adenta', 'Oshiyie', 20.00, true),
  ('Greater Accra', 'Adenta', 'Oyibi', 20.00, true),
  ('Greater Accra', 'Adenta', 'Pantang', 20.00, true),
  ('Greater Accra', 'Adenta', 'Santeo', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Ashaiman', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Ashaiman New Town', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Fadama', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Jericho', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Lebanon', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Old Tulaku', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Roman Down', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Tulaku', 20.00, true),
  ('Greater Accra', 'Ashaiman', 'Zongo', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Circle', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Ministries', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Odaw', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Maamobi', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Nima 441', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Abelenkpe', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Papao', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'West Airport', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Akweteyman', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Mantseman', 20.00, true),
  ('Greater Accra', 'Ga East', 'Abetinso', 20.00, true),
  ('Greater Accra', 'Ga East', 'Asaprochona', 20.00, true),
  ('Greater Accra', 'Ga East', 'Dome-Kwabenya', 20.00, true),
  ('Greater Accra', 'Ga East', 'Huapa', 20.00, true),
  ('Greater Accra', 'Ga East', 'Legon', 20.00, true),
  ('Greater Accra', 'Ga East', 'Nsuobri', 20.00, true),
  ('Greater Accra', 'Ga East', 'Osuwem', 20.00, true),
  ('Greater Accra', 'Ga East', 'Papase', 20.00, true),
  ('Greater Accra', 'Ga East', 'Teiman', 20.00, true),
  ('Greater Accra', 'Ga North', 'Amomole', 20.00, true),
  ('Greater Accra', 'Ga North', 'Ayikai Doblo', 20.00, true),
  ('Greater Accra', 'Ga North', 'Fise', 20.00, true),
  ('Greater Accra', 'Ga North', 'Kofikrom', 20.00, true),
  ('Greater Accra', 'Ga North', 'Kotoku', 20.00, true),
  ('Greater Accra', 'Ga North', 'Mayera', 20.00, true),
  ('Greater Accra', 'Ga North', 'Tantra Hill', 20.00, true),
  ('Greater Accra', 'Ga South', 'Ashalaja', 20.00, true),
  ('Greater Accra', 'Ga South', 'Bojo', 20.00, true),
  ('Greater Accra', 'Ga South', 'Buaku', 20.00, true),
  ('Greater Accra', 'Ga South', 'Chuim', 20.00, true),
  ('Greater Accra', 'Ga South', 'Danchira', 20.00, true),
  ('Greater Accra', 'Ga South', 'Langma', 20.00, true),
  ('Greater Accra', 'Ga South', 'Obakrowa', 20.00, true),
  ('Greater Accra', 'Ga South', 'Obeyeyie', 20.00, true),
  ('Greater Accra', 'Ga South', 'Tsokomey', 20.00, true),
  ('Greater Accra', 'Ga South', 'West Hills', 20.00, true),
  ('Greater Accra', 'Ga West', 'Abominya', 20.00, true),
  ('Greater Accra', 'Ga West', 'Adjen Kotoku', 20.00, true),
  ('Greater Accra', 'Ga West', 'Anumle', 20.00, true),
  ('Greater Accra', 'Ga West', 'Apenkwa', 20.00, true),
  ('Greater Accra', 'Ga West', 'Gonse', 20.00, true),
  ('Greater Accra', 'Ga West', 'Katapor', 20.00, true),
  ('Greater Accra', 'Ga West', 'Kojo Ashong', 20.00, true),
  ('Greater Accra', 'Ga West', 'Kubekro', 20.00, true),
  ('Greater Accra', 'Ga West', 'Kunyenya', 20.00, true),
  ('Greater Accra', 'Ga West', 'Kutunse', 20.00, true),
  ('Greater Accra', 'Ga West', 'Kwashie Bu', 20.00, true),
  ('Greater Accra', 'Ga West', 'Lupunya', 20.00, true),
  ('Greater Accra', 'Ga West', 'Maajor', 20.00, true),
  ('Greater Accra', 'Ga West', 'Mampehia', 20.00, true),
  ('Greater Accra', 'Ga West', 'Manhean', 20.00, true),
  ('Greater Accra', 'Ga West', 'Medie', 20.00, true),
  ('Greater Accra', 'Ga West', 'Mpehuasem', 20.00, true),
  ('Greater Accra', 'Ga West', 'Nsakina', 20.00, true),
  ('Greater Accra', 'Ga West', 'Oduman', 20.00, true),
  ('Greater Accra', 'Ga West', 'Onyansana', 20.00, true),
  ('Greater Accra', 'Ga West', 'Samsam', 20.00, true),
  ('Greater Accra', 'Ga West', 'Sesemi', 20.00, true),
  ('Greater Accra', 'Ga West', 'Suapa', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Ako Adjei', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Kpehe', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Oxford Street', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Bethlehem', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Dawhenya', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Katamanso', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Zenu', 20.00, true),
  ('Greater Accra', 'Krowor', 'Nungua Old Town', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Airport', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Burma Camp', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'East Cantonments', 20.00, true),
  ('Greater Accra', 'La-Nkwantanang', 'Nkwantanang', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Teshie First Junction', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Teshie Second Junction', 20.00, true),
  ('Greater Accra', 'Madina', 'Abokobi', 20.00, true),
  ('Greater Accra', 'Madina', 'Atomic Junction', 20.00, true),
  ('Greater Accra', 'Madina', 'Ayi Mensah', 20.00, true),
  ('Greater Accra', 'Madina', 'Boi', 20.00, true),
  ('Greater Accra', 'Madina', 'Danfa', 20.00, true),
  ('Greater Accra', 'Madina', 'Madina Zongo', 20.00, true),
  ('Greater Accra', 'Madina', 'Otinibi', 20.00, true),
  ('Greater Accra', 'Madina', 'Oyarifa', 20.00, true),
  ('Greater Accra', 'Madina', 'Ritz Junction', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Afienya', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Ahanya', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Ahwiam', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Alavanyo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Alorkpem', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Amlakpo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Dawa', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Fantevikope', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Kopodor', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Kpatsedor', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Kpetsupanya', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Kpongunor', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Kposi', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Kpotsum', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Lekpongunor', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Miotso', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Mlitsakpo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'New Ningo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Ningo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Ocanseykope', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Old Ningo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Prampram', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Tekpanya', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Tekpekope', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Togbloku', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Totimekope', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Tsopoli', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Vakpo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Wokumagbe', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Akweteman', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Bubiashie', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Kwame Nkrumah Circle', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Adukrom', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Agomeda', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Asutsuare', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Ayetepa', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Ayikuma', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Dodowa', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Juapong', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Kasunya', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Kodiabe', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Kordiabe', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Odumse', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Ogome', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Osudoku', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Shai Hills', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Shai Hills Station', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 21', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 22', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 23', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 24', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 25', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 26', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 27', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 28', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 29', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 30', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 31', 20.00, true),
  ('Greater Accra', 'Tema', 'Community 32', 20.00, true),
  ('Greater Accra', 'Tema', 'Kpone', 20.00, true),
  ('Greater Accra', 'Tema', 'Lashibi', 20.00, true),
  ('Greater Accra', 'Tema', 'Michel Camp', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 1', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 10', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 11', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 12', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 13', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 14', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 15', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 16', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 17', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 18', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 19', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 2', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 20', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 3', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 4', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 5', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 6', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 7', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 8', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Community 9', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Harbour', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema Industrial Area', 20.00, true),
  ('Greater Accra', 'Tema', 'Tema New Town', 20.00, true),
  ('Greater Accra', 'Tema West', 'Community 18', 20.00, true),
  ('Greater Accra', 'Tema West', 'Community 19', 20.00, true),
  ('Greater Accra', 'Tema West', 'Community 20', 20.00, true),
  ('Greater Accra', 'Weija-Gbawe', 'Wiaboman', 20.00, true),
  ('Greater Accra', 'Tema', 'Sakumono', 20.00, true),
  ('Greater Accra', 'Tema', 'Klagon', 20.00, true),
  ('Greater Accra', 'Adenta', 'Ogbojo', 20.00, true),
  ('Greater Accra', 'Adenta', 'Lakeside', 20.00, true),
  ('Greater Accra', 'Madina', 'Madina', 20.00, true),
  ('Greater Accra', 'Madina', 'North Legon', 20.00, true),
  ('Greater Accra', 'Ga East', 'Abokobi', 20.00, true),
  ('Greater Accra', 'Ga East', 'Dome', 20.00, true),
  ('Greater Accra', 'Ga East', 'Taifa', 20.00, true),
  ('Greater Accra', 'Ga East', 'Haatso', 20.00, true),
  ('Greater Accra', 'Ga East', 'Kwabenya', 20.00, true),
  ('Greater Accra', 'Ga East', 'Agbogba', 20.00, true),
  ('Greater Accra', 'Ga East', 'Atomic', 20.00, true),
  ('Greater Accra', 'Ga East', 'Ashongman', 20.00, true),
  ('Greater Accra', 'Ga East', 'Oyarifa', 20.00, true),
  ('Greater Accra', 'Ga East', 'Boi', 20.00, true),
  ('Greater Accra', 'Ga East', 'Pantang', 20.00, true),
  ('Greater Accra', 'Ga North', 'Ofankor', 20.00, true),
  ('Greater Accra', 'Ga North', 'Pokuase', 20.00, true),
  ('Greater Accra', 'Ga North', 'Amasaman', 20.00, true),
  ('Greater Accra', 'Ga North', 'Mile 7', 20.00, true),
  ('Greater Accra', 'Ga North', 'Mile 9', 20.00, true),
  ('Greater Accra', 'Ga West', 'Amasaman', 20.00, true),
  ('Greater Accra', 'Ga West', 'Pokuase', 20.00, true),
  ('Greater Accra', 'Ga West', 'Fise', 20.00, true),
  ('Greater Accra', 'Ga West', 'Ayikai Doblo', 20.00, true),
  ('Greater Accra', 'Ga West', 'Mayera', 20.00, true),
  ('Greater Accra', 'Ga West', 'Anyaa', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Sowutuom', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Lapaz', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Santa Maria', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Awoshie', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Abeka', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Odorkor', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Darkuman', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Kwashieman', 20.00, true),
  ('Greater Accra', 'Ga Central', 'Anyaa', 20.00, true),
  ('Greater Accra', 'Ga Central', 'McCarthy Hill', 20.00, true),
  ('Greater Accra', 'Ga South', 'Weija', 20.00, true),
  ('Greater Accra', 'Ga South', 'Gbawe', 20.00, true),
  ('Greater Accra', 'Ga South', 'Mallam', 20.00, true),
  ('Greater Accra', 'Ga South', 'McCarthy Hill', 20.00, true),
  ('Greater Accra', 'Ga South', 'Bortianor', 20.00, true),
  ('Greater Accra', 'Ga South', 'Kokrobite', 20.00, true),
  ('Greater Accra', 'Ga South', 'Ngleshie Amanfrom', 20.00, true),
  ('Greater Accra', 'Ga South', 'Aplaku', 20.00, true),
  ('Greater Accra', 'Ga South', 'Oblogo', 20.00, true),
  ('Greater Accra', 'Ga South', 'Tetegu', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Lartebiokorshie', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Odorkor', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Darkuman', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Awoshie', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Anyaa', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Lapaz', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Kaneshie', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Abossey Okai', 20.00, true),
  ('Greater Accra', 'Ablekuma Central', 'Mataheko', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Darkuman', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Odorkor', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Tesano', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Abeka', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Achimota', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Kwashieman', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Lartebiokorshie', 20.00, true),
  ('Greater Accra', 'Ablekuma North', 'Kaneshie', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Dansoman', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Mataheko', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Mamprobi', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Korle Gonno', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Chorkor', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Glefe', 20.00, true),
  ('Greater Accra', 'Ablekuma West', 'Gbawe', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Abeka', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Tesano', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Achimota', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Akweteyman', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Alajo', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Kotobabi', 20.00, true),
  ('Greater Accra', 'Okaikwei North', 'Mile 7', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Kokomlemle', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Asylum Down', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Kanda', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Ridge', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Adabraka', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'North Ridge', 20.00, true),
  ('Greater Accra', 'Ayawaso Central', 'Accra New Town', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Nima', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Kotobabi', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Kanda', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Accra New Town', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Mamobi', 20.00, true),
  ('Greater Accra', 'Ayawaso East', 'Alajo', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Accra New Town', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Tesano', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Kotobabi', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Nima', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Maamobi', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Alajo', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Pig Farm', 20.00, true),
  ('Greater Accra', 'Ayawaso North', 'Avenor', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Dzorwulu', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Abelemkpe', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Roman Ridge', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Airport Residential', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Tesano', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Achimota', 20.00, true),
  ('Greater Accra', 'Ayawaso West', 'Shiashie', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Osu', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Ridge', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Adabraka', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Ringway', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Asylum Down', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Ministries', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'North Ridge', 20.00, true),
  ('Greater Accra', 'Korle Klottey', 'Victoriaborg', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'La', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Labadi', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Labone', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Cantonments', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Osu', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Trade Fair', 20.00, true),
  ('Greater Accra', 'La Dade-Kotopon', 'Teshie', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Teshie', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Nungua', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Nungua Estates', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Baatsona', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Sakumono', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Spintex', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Trade Fair', 20.00, true),
  ('Greater Accra', 'Ledzokuku', 'Burma Camp', 20.00, true),
  ('Greater Accra', 'Krowor', 'Nungua', 20.00, true),
  ('Greater Accra', 'Krowor', 'Nungua Estates', 20.00, true),
  ('Greater Accra', 'Krowor', 'Lashibi', 20.00, true),
  ('Greater Accra', 'Krowor', 'Sakumono', 20.00, true),
  ('Greater Accra', 'Krowor', 'Baatsona', 20.00, true),
  ('Greater Accra', 'Krowor', 'Spintex', 20.00, true),
  ('Greater Accra', 'Krowor', 'Klagon', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 2', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 3', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 4', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 5', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 6', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 7', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 8', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 9', 20.00, true),
  ('Greater Accra', 'Tema West', 'Tema Community 10', 20.00, true),
  ('Greater Accra', 'Tema West', 'Sakumono', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Kpone', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Santeo', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Oyibi', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Community 25', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Community 26', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Klagon', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Lashibi', 20.00, true),
  ('Greater Accra', 'Kpone-Katamanso', 'Michel Camp', 20.00, true),
  ('Greater Accra', 'Ada West', 'Sege', 20.00, true),
  ('Greater Accra', 'Ada West', 'Ada Foah', 20.00, true),
  ('Greater Accra', 'Ada West', 'Goi', 20.00, true),
  ('Greater Accra', 'Ada West', 'Toflokpo', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Dawhenya', 20.00, true),
  ('Greater Accra', 'Ningo-Prampram', 'Zongo', 20.00, true),
  ('Greater Accra', 'Shai-Osudoku', 'Doryumu', 20.00, true)
ON CONFLICT (lower(trim(region)), lower(trim(coalesce(city, ''))), lower(trim(coalesce(town, ''))))
DO UPDATE SET
  city = EXCLUDED.city,
  town = EXCLUDED.town,
  is_active = true;
